name: Deploy to Heroku

on: #deploy event triggered only on push and pull request event happen on main branch
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: akhileshns/heroku-deploy@v3.13.15
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
        heroku_email: ${{secrets.HEROKU_MAIL}}